// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDixgjIiIwY8MLV82P_UXY5fn5jbSYEi-Y',
    appId: '1:488746407188:web:e2dde35822a659bed65e01',
    messagingSenderId: '488746407188',
    projectId: 'chatsap-f65b5',
    authDomain: 'chatsap-f65b5.firebaseapp.com',
    storageBucket: 'chatsap-f65b5.appspot.com',
    measurementId: 'G-H7J1SLEBD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfceHAaKR7Cfb5vZDkPdWDYYc2hyGqj14',
    appId: '1:488746407188:android:da79944edaec7c0bd65e01',
    messagingSenderId: '488746407188',
    projectId: 'chatsap-f65b5',
    storageBucket: 'chatsap-f65b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpVPnj0C0sQgoqQfDhm7tFJ6y03XEvOX0',
    appId: '1:488746407188:ios:04d4d2a703722b79d65e01',
    messagingSenderId: '488746407188',
    projectId: 'chatsap-f65b5',
    storageBucket: 'chatsap-f65b5.appspot.com',
    iosClientId: '488746407188-057al6n4l1tu0g42binfffo5n0ok6rqi.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
